# Generated by Django 3.1.3 on 2021-11-30 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarGroup',
            fields=[
                ('car_group_id', models.CharField(db_column='car_group_id', max_length=20, primary_key=True, serialize=False, verbose_name='车队编号')),
                ('carGroupCode', models.CharField(db_column='car_group_code', max_length=50, verbose_name='车队代码(唯一)')),
                ('car_group_full_name', models.CharField(db_column='car_group_full_name', max_length=100, verbose_name='车队全称')),
                ('car_group_eng_full_name', models.CharField(db_column='car_group_eng_full_name', max_length=100, verbose_name='英文全称')),
                ('car_group_short_name', models.CharField(db_column='car_group_short_name', max_length=15, verbose_name='中文简称')),
                ('address', models.CharField(db_column='address', max_length=200, verbose_name='地址')),
                ('contacts', models.CharField(db_column='contacts', max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(db_column='contact_phone', max_length=20, verbose_name='联系电话')),
                ('fax', models.CharField(db_column='fax', max_length=20, verbose_name='传真')),
                ('type', models.CharField(db_column='type', max_length=10, verbose_name='车队类型')),
                ('lift_container_number', models.IntegerField(db_column='lift_container_number', max_length=6, verbose_name='可提TEU数量')),
                ('lift_heavy_container_number', models.IntegerField(db_column='lift_heavy_container_number', max_length=6, verbose_name='可提重TEU数量')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargroup_create_by_user', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargroup_update_by_user', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'db_table': '车队表',
                'managed': (False,),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('login_name', models.CharField(db_column='login_name', max_length=50, verbose_name='登录名')),
                ('password', models.CharField(db_column='password', max_length=100, verbose_name='密码')),
                ('user_type', models.CharField(db_column='user_type', max_length=20, verbose_name='用户类型（车队方、财务等）')),
                ('car_group_id', models.CharField(db_column='car_group_id', max_length=20, verbose_name='如果是车队业务员，则关联到对应车队')),
                ('B_or_C', models.CharField(choices=[('B', 'B端'), ('C', '_c端')], db_column='B_or_C', max_length=1, verbose_name='用户类型2（B端或C端）')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_create_by_user', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_update_by_user', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'db_table': '系统用户表',
                'managed': (False,),
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.CharField(db_column='plan_id', max_length=20, primary_key=True, serialize=False, verbose_name='计划号')),
                ('plan_time', models.DateTimeField(db_column='plan_time', verbose_name='预约时间')),
                ('expiryDate', models.DateTimeField(db_column='expiry_date', verbose_name='过期时间')),
                ('vesselName', models.CharField(db_column='vessel_name', max_length=50, verbose_name='船名')),
                ('toWhere', models.CharField(db_column='to_where', max_length=10, verbose_name='去向')),
                ('portOfFinal', models.CharField(db_column='port_of_final', max_length=10, verbose_name='目的港')),
                ('voyage', models.CharField(db_column='voyage', max_length=50, verbose_name='航次')),
                ('depot', models.CharField(db_column='depot', max_length=4, verbose_name='堆场代码')),
                ('blNo', models.CharField(db_column='bl_no', max_length=50, verbose_name='提单号')),
                ('operCode', models.CharField(db_column='oper_code', max_length=20, verbose_name='所属客户')),
                ('plan_status', models.CharField(db_column='plan_status', max_length=20, verbose_name='预约状态')),
                ('payment_status', models.CharField(db_column='payment_status', max_length=20, verbose_name='缴费状态')),
                ('document_path', models.CharField(db_column='document_path', max_length=1000, verbose_name='提箱单图片地址')),
                ('remark', models.CharField(db_column='remark', max_length=500, verbose_name='备注')),
                ('KS_code', models.CharField(db_column='KS_code', max_length=100, verbose_name='KS码')),
                ('carGroupCode', models.ForeignKey(db_column='car_group_code', max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='app.cargroup', verbose_name='所属车队（外键）')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_create_by_user', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_update_by_user', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'db_table': '预约计划表',
                'managed': (False,),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_no', models.CharField(db_column='invoice_no', max_length=20, primary_key=True, serialize=False, verbose_name='发票号')),
                ('money', models.CharField(db_column='money', max_length=20, verbose_name='交易金额')),
                ('pay_time', models.DateTimeField(db_column='pay_time', verbose_name='交易时间')),
                ('pay_type', models.CharField(db_column='pay_type', max_length=10, verbose_name='交易类型（小程序或者网页端）')),
                ('pay_from', models.CharField(db_column='pay_from', max_length=50, verbose_name='支付来源')),
                ('return_status', models.CharField(db_column='return_status', max_length=50, verbose_name='退款状态')),
                ('return_no', models.CharField(db_column='return_no', max_length=20, verbose_name='退款流水号')),
                ('return_money_apply', models.CharField(db_column='return_money_apply', max_length=20, verbose_name='申请退款金额')),
                ('return_money_actual', models.CharField(db_column='return_money_actual', max_length=20, verbose_name='实际退款金额')),
                ('return_remark', models.CharField(db_column='return_remark', max_length=50, verbose_name='退款说明')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_create_by_user', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('plan_id', models.ForeignKey(db_column='plan_id', max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='app.plan', verbose_name='所属计划')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_update_by_user', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'db_table': '支付费用表',
                'managed': (False,),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('imager_id', models.CharField(db_column='imager_id', max_length=20, primary_key=True, serialize=False, verbose_name='图片编号')),
                ('images_path', models.CharField(db_column='images_path', max_length=20, verbose_name='图片地址')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_create_by_user', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('plan_id', models.ForeignKey(db_column='plan_id', max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='app.plan', verbose_name='所属计划')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_update_by_user', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'db_table': '提箱单图片表',
                'managed': (False,),
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('fee_id', models.CharField(db_column='fee_id', max_length=20, primary_key=True, serialize=False, verbose_name='费用编号')),
                ('fee_name', models.CharField(db_column='fee_name', max_length=20, verbose_name='费用名称')),
                ('quantity', models.IntegerField(db_column='quantity', max_length=6, verbose_name='数量')),
                ('unit', models.CharField(db_column='unit', max_length=10, verbose_name='单位')),
                ('unit_price', models.FloatField(db_column='unit_price', verbose_name='单价')),
                ('price', models.FloatField(db_column='price', verbose_name='总价')),
                ('invoice_id', models.CharField(db_column='invoice_id', max_length=20, verbose_name='所属交易流水（外键）')),
                ('container_no', models.CharField(db_column='container_no', max_length=20, verbose_name='集装箱箱号')),
                ('pay_status', models.CharField(db_column='pay_status', max_length=20, verbose_name='缴费状态')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_create_by_user', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('plan_id', models.ForeignKey(db_column='plan_id', max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='app.plan', verbose_name='所属计划')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_update_by_user', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'db_table': '支付费用明细表',
                'managed': (False,),
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('container_id', models.CharField(db_column='container_id', max_length=20, primary_key=True, serialize=False, verbose_name='集装箱编号')),
                ('container_no', models.CharField(db_column='container_no', max_length=20, verbose_name='集装箱箱号')),
                ('contSize', models.CharField(db_column='cont_size', max_length=10, verbose_name='尺寸')),
                ('contType', models.CharField(db_column='cont_type', max_length=10, verbose_name='箱型')),
                ('ctn_net_weight', models.FloatField(db_column='ctn_net_weight', verbose_name='净重')),
                ('ctn_gross_weight', models.FloatField(db_column='ctn_gross_weight', verbose_name='毛重')),
                ('ctn_cy_no', models.CharField(db_column='ctn_cy_no', max_length=50, verbose_name='箱系统号')),
                ('enter_time', models.DateTimeField(db_column='enter_time', verbose_name='进场时间')),
                ('serialNo', models.CharField(db_column='serial_no', max_length=20, verbose_name='授权码')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_create_by_user', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('plan_id', models.ForeignKey(db_column='plan_id', max_length=20, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.plan', verbose_name='所属计划（外键）')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_update_by_user', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'db_table': '箱列表',
                'managed': (False,),
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('action_id', models.CharField(db_column='action_id', max_length=20, primary_key=True, serialize=False, verbose_name='操作编号')),
                ('action_name', models.CharField(db_column='action_name', max_length=20, verbose_name='操作名称')),
                ('action_time', models.DateTimeField(db_column='action_time', verbose_name='操作时间')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_create_by_user', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('plan_id', models.ForeignKey(db_column='plan_id', max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='app.plan', verbose_name='计划编号')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_update_by_user', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('user_id', models.ForeignKey(db_column='user_id', max_length=10, on_delete=django.db.models.deletion.DO_NOTHING, to='app.user', verbose_name='操作人')),
            ],
            options={
                'db_table': '操作记录表',
                'managed': (False,),
            },
        ),
    ]
