# Generated by Django 3.1.3 on 2021-09-30 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'managed': (False,)},
        ),
        migrations.AlterModelOptions(
            name='cargroup',
            options={'managed': (False,)},
        ),
        migrations.AlterModelOptions(
            name='container',
            options={'managed': (False,)},
        ),
        migrations.AlterModelOptions(
            name='fee',
            options={'managed': (False,)},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'managed': (False,)},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'managed': (False,)},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'managed': (False,)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': (False,)},
        ),
        migrations.AlterField(
            model_name='action',
            name='planId',
            field=models.ForeignKey(db_column='plan_id', max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='app.plan', verbose_name='计划编号'),
        ),
        migrations.AlterField(
            model_name='action',
            name='userId',
            field=models.ForeignKey(db_column='user_id', max_length=10, on_delete=django.db.models.deletion.DO_NOTHING, to='app.user', verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='planId',
            field=models.ForeignKey(db_column='plan_id', max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='app.plan', verbose_name='所属计划'),
        ),
        migrations.AlterField(
            model_name='image',
            name='planId',
            field=models.ForeignKey(db_column='plan_id', max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='app.plan', verbose_name='所属计划'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='planId',
            field=models.ForeignKey(db_column='plan_id', max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='app.plan', verbose_name='所属计划'),
        ),
        migrations.AlterModelTable(
            name='action',
            table='操作记录表',
        ),
        migrations.AlterModelTable(
            name='cargroup',
            table='车队表',
        ),
        migrations.AlterModelTable(
            name='container',
            table='箱列表',
        ),
        migrations.AlterModelTable(
            name='fee',
            table='支付费用明细表',
        ),
        migrations.AlterModelTable(
            name='image',
            table='提箱单图片表',
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='支付费用表',
        ),
        migrations.AlterModelTable(
            name='plan',
            table='预约计划表',
        ),
        migrations.AlterModelTable(
            name='user',
            table='系统用户表',
        ),
    ]
