# Generated by Django 3.1.3 on 2021-11-27 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='user_id',
            new_name='operCode',
        ),
    ]
