# Generated by Django 3.1.3 on 2021-11-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211127_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='operCode',
            field=models.CharField(db_column='oper_code', max_length=20, verbose_name='所属客户'),
        ),
    ]
