# Generated by Django 3.1.3 on 2021-11-30 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211130_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='user_id',
        ),
        migrations.AddField(
            model_name='action',
            name='id',
            field=models.ForeignKey(db_column='id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.user', verbose_name='操作人'),
            preserve_default=False,
        ),
    ]
