# Generated by Django 3.1.3 on 2021-11-27 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211127_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargroup',
            old_name='car_group_code',
            new_name='carGroupCode',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='car_group_code',
            new_name='carGroupCode',
        ),
    ]
