# Generated by Django 3.1.3 on 2021-11-30 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211130_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='action',
            name='id',
        ),
        migrations.AddField(
            model_name='action',
            name='user_id',
            field=models.ForeignKey(db_column=' id', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='app.user', verbose_name='操作人'),
            preserve_default=False,
        ),
    ]
