# Generated by Django 3.1.3 on 2021-11-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211127_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargroup',
            old_name='carGroupCode',
            new_name='car_group_code',
        ),
    ]
