# Generated by Django 3.1.3 on 2021-11-27 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211127_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargroup',
            old_name='car_group_code',
            new_name='carGroupCode',
        ),
    ]
